name: "AWX Deployment Trigger"
description: "Triggers a deployment on Ansible AWX and waits for the result"

inputs:
  AWX_URL:
    description: "The URL for the Ansible AWX instance"
    required: true
  AWX_TOKEN:
    description: "The API token for authenticating with AWX"
    required: true
  AWX_TEMPLATE_ID:
    description: "The Job Template ID to trigger in AWX"
    required: true

runs:
  using: "node16"
  main: "index.js"
