- name: Gather topology descriptrs files from topologies folder
  hosts: localhost
  vars:
    testbed_repo: "https://github.com/TheDarkPyotr/ansible-tests"
    testbed_repo_branch: "main"
  tasks:
    - name: Create a temporary directory for testbed files
      ansible.builtin.tempfile:
        state: directory
        suffix: _testbed_repo
      register: temp_repo_dir

    - name: Clone the testbed repository
      ansible.builtin.git:
        repo: "{{ testbed_repo }}"
        dest: "{{ temp_repo_dir.path }}"
        version: "{{ testbed_repo_branch }}" # Branch of testbed repository
        force: true

    - name: Checkout the specific commit
      ansible.builtin.command:
        cmd: git checkout HEAD
        chdir: "{{ temp_repo_dir.path }}"
      register: git_checkout

    - name: Ensure the commit checkout
      ansible.builtin.assert:
        that:
          - git_checkout.rc == 0
        fail_msg: "Failed to checkout commit {{ commit }}"

      register: files
    - name: Find files in directory
      find:
        paths: "{{ temp_repo_dir.path }}"
        recurse: true
        patterns: "*.json"
      register: files

    - name: Launch execution pipeline
      awx.awx.workflow_launch:
        workflow_template: "Oakestra Testbed Execution Pipeline [WIP]"
        extra_vars:
          topology_descriptor: "{{ item.path }}"
          commit: "HEAD"
          branch: "main"
        wait: false
      loop: "{{ files.files }}"
      delegate_to: localhost
