name: Preliminary Checks

on:
    pull_request_review:
      types: [submitted]

jobs:
  check:
    name: Testbed Oneshot Execution
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
        - name: Wait for tests to succeed
          uses: lewagon/wait-on-check-action@v1.3.4
          with:
              ref: ${{ github.ref }}
              check-name: 'Trigger Testbed Oneshot Execution'
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              wait-interval: 20