name: Preliminary Checks

on:
    pull_request_review:
      types: [submitted]

jobs:
  check:
    name: Testbed Oneshot Execution
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
        - name: Print github ref
          run: echo "Github ref ${{ github.ref }}"
        - name: Print github sha
          run: echo "Github sha ${{ github.sha }}"
        - name: Wait for tests to succeed
          uses: lewagon/wait-on-check-action@v1.3.4
          with:
              ref: ${{ github.sha }}
              check-name: 'Trigger Testbed Oneshot Execution'
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              wait-interval: 20