name: trigger_testbed
on:
  workflow_run:
    workflows: ["Preliminary Checks"]
    types:
      - requested

jobs:
  trigger_testbed:
    runs-on: ubuntu-latest
    steps:
      - name: Run on workflow A success
        run: echo "Workflow A completes successfully"
      - name: Print event branch
        run: echo "Workflow A run ID ${{ github.event.workflow_run.head_branch }} "
      - name: Print event sha
        run: echo "Workflow A run commit ${{ github.event.workflow_run.head_sha }} "
      - name: Print event  commit
        run: echo "Workflow A run branch ${{ github.event.workflow_run.head_commit }} "
      - name: Print triggering_actor
        run: echo "Workflow A run triggering actor ${{ github.event.workflow_run.actor.login }} "
      - name: Print event name
        run: echo "Workflow A run event ${{ github.event.workflow_run.event }} "
      - name: Print event id
        run: echo "Workflow A name ${{ github.event.workflow_run.name }} "
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./.github/actions/awx-deploy

      - name: Trigger Testbed Oneshot Execution
        uses: ./.github/actions/awx-deploy
        with:
          AWX_URL: ${{ secrets.TOWER_HOST }}
          AWX_TOKEN: ${{ secrets.TOWER_TOKEN }}
          AWX_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          PR_BRANCH: ${{ github.event.workflow_run.head_branch }}
          PR_USER: ${{ github.event.workflow_run.actor.login }}
          PR_COMMIT: ${{ github.event.workflow_run.head_sha }}
